MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './pretrain/vit_image_net_224.pth' 
  METRIC_LOSS_TYPE: 'triplet_ss'
  ID_LOSS_TYPE: 'softmax'
  IF_FEAT_CAT : False
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: False
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  
INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: ('/mnt/hdd_data/Dataset')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  SCHEDULER_NAME: 'cos'
  MAX_EPOCHS: 120
  BASE_LR: 0.0003
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 20
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: False
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: './logs/market_vit_base_256_128/101/transformer_120_101.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  VISUALIZE : False
  VISUALIZE_INDEX : 777
  VISUALIZE_RANK : 10
  VISUALIZE_TYPE : 0 # 0 : Specific query index, 1: Max Error ID , 2: Max Distance Query 
  VISUALIZE_METRIC : 'Euclidean'
  HEAD_FUSION: 'mean'
  DISCARD_RATIO : 0.9
  EVAL_METRIC: 'Euclidean'
  EXPLAIN : False

OUTPUT_DIR: './logs/market_vit_base_256_128'
INDEX : 9999
WANDB : False
