  # triplet_ss_1 : loss_abs(CLS) version
  # triplet_ss_2 : loss_abs(cls_param) 0509
  # triplet_ss_pos_1 : loss_cls_mean + loss_abs(CLS) + loss_dist
  # triplet_ss_pos_2 : loss_cls_mean + loss_abs(CLS) + JSD
  # triplet_ss_pos_3 : triplet + JSD(CLS)
  # triplet_ss_pos_4 : triplet + JSD(cls_param)
  # triplet_ss_pos_5 : loss_abs(CLS) or triplet + JSD(head_wise)
  # triplet_ss_pos_6 : loss_abs or triplet + JSD(head_wise, cls_weight)
  # triplet_ss_pos_7 : loss(cls_weight) + JSD(head_wise, cls_weight)
MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_HW_RATIO: 2
  PRETRAIN_PATH: './pretrain/vit_base_ics_cfs_lup.pth' 
  METRIC_LOSS_TYPE: 'triplet'
  ID_LOSS_TYPE: 'softmax'
  IF_FEAT_CAT : False
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID_SSL'
  STRIDE_SIZE: [16, 16]
  STEM_CONV: True
  REL_POS : False
  REL_CLS : False
  REL_ABS : False
  ABS_POS : True
  HEAD_NUM : 12

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
DATASETS:
  NAMES: ('msmt17')
  ROOT_DIR: ('/home/sungsu21/TransReID/TransReID/dataset')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4 # Number of samples for each ID
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  SCHEDULER_NAME: 'cos'
  MAX_EPOCHS: 120
  BASE_LR: 0.0004
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 20
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  PATCH_RATIO : [0.5,0.5]
  LOSS_RATIO : 0.5
  FEAT_NORM : False
  JSD : True
  HEAD_WISE : False
  COMB : True
  REPLACEMENT : True
  COMB_INDEX : 5
TEST:
  EVAL: False
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: './logs/market_vit_base_256_128/101/transformer_120_101.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  VISUALIZE : False
  VISUALIZE_INDEX : 777
  VISUALIZE_RANK : 10
  VISUALIZE_TYPE : 0 # 0 : Specific query index, 1: Max Error ID , 2: Max Distance Query 
  VISUALIZE_METRIC : 'Euclidean'
  HEAD_FUSION : 'mean'
  DISCARD_RATIO : 0.9
  EVAL_METRIC : 'Euclidean'
  EXPLAIN : False

OUTPUT_DIR: './logs/msmt17_vit_base_384_128'
INDEX : 604
WANDB : True